// Builds dist/Code.gs: the server (src/server) with the browser app
// (src/client) inlined as one HTML string. It is the only file Apps Script needs.
import { build as esbuild } from "esbuild";
import { build as vite } from "vite";
import fs from "node:fs";

fs.mkdirSync("dist", { recursive: true });

// Apps Script only calls real top level functions, so the bundle sits in one
// global object and these stubs forward to it.
const ENTRY_POINTS = ["doGet", "api", "setup", "loadDemoData", "acceloDryRun", "acceloImport"];

// Browser app first, so the server bundle can carry it.
await vite({ configFile: "vite.config.ts", logLevel: "warn" });
const html = fs.readFileSync("build/client/index.html", "utf8");

const server = await esbuild({
  entryPoints: ["src/server/main.ts"],
  bundle: true,
  format: "iife",
  globalName: "LW",
  target: "es2020",
  platform: "neutral",
  write: false,
  legalComments: "none",
  define: { INDEX_HTML: JSON.stringify(html) },
});
const stubs = ENTRY_POINTS.map((n) => `function ${n}() { return LW.${n}.apply(null, arguments); }`).join("\n");
fs.writeFileSync(
  "dist/Code.gs",
  `// LAIRE Workspace. Generated by npm run build. Paste this whole file into Apps Script.\n${server.outputFiles[0].text}\n${stubs}\n`,
);
for (const old of ["dist/Index.html", "dist/appsscript.json"]) fs.rmSync(old, { force: true });

const kb = (f) => `${Math.round(fs.statSync(f).size / 1024)} KB`;
console.log(`dist/Code.gs ${kb("dist/Code.gs")} (app ${Math.round(html.length / 1024)} KB)`);
