// Builds the two files Apps Script needs into dist/:
//   Code.gs     the server (src/server), bundled
//   Index.html  the browser app (src/client), one self contained file
import { build as esbuild } from "esbuild";
import { build as vite } from "vite";
import fs from "node:fs";

fs.mkdirSync("dist", { recursive: true });

// Apps Script only calls real top level functions, so the bundle sits in one
// global object and these stubs forward to it.
const ENTRY_POINTS = ["doGet", "api", "setup", "loadDemoData", "acceloDryRun", "acceloImport"];

const server = await esbuild({
  entryPoints: ["src/server/main.ts"],
  bundle: true,
  format: "iife",
  globalName: "LW",
  target: "es2020",
  platform: "neutral",
  write: false,
  legalComments: "none",
});
const stubs = ENTRY_POINTS.map((n) => `function ${n}() { return LW.${n}.apply(null, arguments); }`).join("\n");
fs.writeFileSync(
  "dist/Code.gs",
  `// LAIRE Workspace server. Generated by npm run build from src/server. Do not edit here.\n${server.outputFiles[0].text}\n${stubs}\n`,
);

await vite({ configFile: "vite.config.ts", logLevel: "warn" });
fs.copyFileSync("build/client/index.html", "dist/Index.html");

fs.writeFileSync(
  "dist/appsscript.json",
  JSON.stringify(
    {
      timeZone: "America/Chicago",
      runtimeVersion: "V8",
      exceptionLogging: "STACKDRIVER",
      webapp: { executeAs: "USER_DEPLOYING", access: "ANYONE_ANONYMOUS" },
    },
    null,
    2,
  ) + "\n",
);

const kb = (f) => `${Math.round(fs.statSync(f).size / 1024)} KB`;
console.log(`dist/Code.gs ${kb("dist/Code.gs")}, dist/Index.html ${kb("dist/Index.html")}`);
